---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Disciplina: Gráficos Científicos no R 

Repositório com scripts, dados e exercícios da disciplina de Gráficos Científicos no R  

__Docente:__ `Gustavo Brant Paterno` (paternogbc@gmail.com)

> Aprenda como organizar bancos de dados e representar os seus resultados através de gráficos bonitos, reproduzíveis, eficientes e com qualidade para publicação nas melhores revistas científicas.

## Escopo 

A disciplina Gráficos Científicos no R irá abordar de forma instrumental as noções básicas para a construção de gráficos de alta qualidade para publicação científica utilizando o software estatístico R, em especial a gramática dos gráficos (`ggplot2`). No curso, teremos uma introdução sobre gestão, limpeza, análise exploratória, organização e preservação de bancos de dados no R (utilizando projetos estruturados no Rstudio). Na sequência, iremos nos aprofundar na teoria da representação gráfica e aprender como produzir gráficos que representem os seus resultados e análises de forma correta, clara e elegante. O objetivo da disciplina é que você termine sabendo: (i) como organizar e gerir seus dados no R e (ii) como construir o gráfico ideal para representar seus resultados e direcionar os leitores dos seus artigos para a mensagem principal do seu trabalho.

## Pacotes necessários

Para acompanhar este curso você precisa instalar diversos pacotes de R 
[lista de pacotes necessários](https://github.com/paternogbc/disciplina-graficos-r/blob/master/R/pacotes_necessarios.R)

*** 

# Links e referências úteis

Alguns links importantes para aprofundamento ao longo da disciplina.

* [Conheça o Tidyverse](https://www.tidyverse.org/packages/)

* [Conceito de tidy data](http://vita.had.co.nz/papers/tidy-data.html)

* [Manual do ggplot2](https://ggplot2.tidyverse.org)

* [RStudio Cheat Sheets](https://rstudio.com/resources/cheatsheets/)

* [Software Carpentry](https://github.com/swcarpentry/swcarpentry)

# Templates

- [Projeto Estruturado Rstudio](https://github.com/paternogbc/template-rstd-project)

# Slides Aulas

- [Aula 1 - Organização de projetos reproduzíveis](https://docs.google.com/presentation/d/1Px9Npa_ANqmmfjCXo9A-eBmWzgUmmkCKd7fBIq_gG6k/edit?usp=sharing)
- [Aula 2 - Organização de dados](https://docs.google.com/presentation/d/1dC9hBTRHp9jFv3oBJKAVW_sESqlUDoLFO4FJWV2uVtM/edit?usp=sharing)
- [Aula 3 - Manipulação de dados](https://docs.google.com/presentation/d/1DqUBvR2-QZQwU4JC0pjT2Vbi5qfZGYCvSJ9wGy2BwLo/edit?usp=sharing)
- [Aula 4 - Introduçao ao Rmarkdown](https://docs.google.com/presentation/d/1DCOQPQ4_BnkeoZ6urt_gkncNU_BZrPga9Fjxhnwg8Xg/edit?usp=sharing)
- [Aula 5 - Introdução a teoria gráfica](https://docs.google.com/presentation/d/1L8nNj6KWYEewFzCCn-krAFWAV-Z_fsPnhncUhX-lmuU/edit?usp=sharing)
- [Aula 6 - Introdução ao ggplot2](https://docs.google.com/presentation/d/19FbbQvEo2YaM-y9unC96L2GjkqKQ8S0PzU4HQX-rJE4/edit?usp=sharing)
- [Aula 7 - Introdução ao uso de cores](https://docs.google.com/presentation/d/15vxUUZnNBGsamxkkfuW1O0S_8DtxrMtcuGTmZ8ABSp4/edit?usp=sharing)
- [Aula 9 - Finalização de gráficos](https://docs.google.com/presentation/d/1K4FMde3kOEDBiXGqZcBEtYB7sLOUgF_3F3H-NbX8yIA/edit?usp=sharing)

# Trabalho de final do curso
- [Roteiro](https://docs.google.com/presentation/d/16_tjwvnr-IPkQ48NaZL23VwlUPkXP8DB0Wg7SnYAL3c/edit?usp=sharing)
- [Modelo apresentação](https://docs.google.com/presentation/d/1AUsfZo-dCBWnL7xJwCT1-uql4jxQ4o4Pwz76ASDIyQI/edit?usp=sharing)